#10 로그인 페이지 퍼블리싱
GiSeok-Hong/wonderart-crm pull request #16
Opened 2023-07-31 14:13 UTC by fepanbr

# #10 로그인 페이지 퍼블리싱
## 작업 목적
- 로그인 페이지 디자인 반영
## 작업 내용
- 로그인 페이지 UI 개발

## 해당 PR에서 테스트할 방법을 작성해 주세요
- 디자인적으로 어색한 부분을 말씀해주세요.

## 첨부
![스크린샷 2023-07-31 오후 11 12 51](https://github.com/GiSeok-Hong/wonderart-crm/assets/20733450/f047e5db-60d3-4735-a1f1-c0b67e9aa749)

## 관련된 이슈, 커밋, PR

- ISSUE #10

## 체크리스트

- [ ] 빌드 체크 하셨나요?
- [ ] 허스키는 정상 작동했나요?
- [ ] PR의 내용을 짐작할 수 있는 적절한 제목을 썼나요?
- [ ] 작업 목적은 명확하게 의미 전달이 가능한가요?
- [ ] 작업 내용은 간결하게 끝나는 문장인가요?
- [ ] 첨부는 기능을 충분히 포함하고 있나요?
- [ ] 관련 이슈나 티켓, PR을 포함했나요?

2023-07-31 14:32 UTC, GiSeok-Hong requested changes

2023-07-31 14:32 UTC, GiSeok-Hong commented on .env
.env 파일까지 같이 올라왔습니다.

해당 파일은 제외해주세요

2023-08-01 23:44 UTC, fepanbr commented on .env
제거한 파일입니다. 감사합니다.

2023-08-01 23:51 UTC, GiSeok-Hong approved these changes
고생하셨습니다

2023-08-01 23:53 UTC, merged