Wonderart-CRM #37 학원생 등록 API 개발
GiSeok-Hong/wonderart-crm pull request #41
Opened 2023-08-28 18:59 UTC by GiSeok-Hong

# Wonderart-CRM #37 학원생 등록 API 개발

## 작업 목적

- 입학원서 페이지에서 사용할 학원생 추가 API 개발

## 작업 내용

- 학원생 추가 api 기능 구현
- react-hook-form (v7.45.4) 추가

## 해당 PR에서 테스트할 방법을 작성해 주세요

- 새로운 패키지가 추가 되었으므로 npm i 명령어 실행 후 개발자 모드를 실행해주세요.
- 입학원서 페이지에서 데이터를 입력 후 등록 버튼을 눌러주세요.

## 첨부

![화면 캡처 2023-08-29 035004](https://github.com/GiSeok-Hong/wonderart-crm/assets/48499094/d7f7bcfe-96a5-40da-b0ed-64edfb401e80)
![화면 캡처 2023-08-29 035807](https://github.com/GiSeok-Hong/wonderart-crm/assets/48499094/1ded25db-8156-4d81-9689-716c85c7bbb4)

## 관련된 이슈, 커밋, PR

- ISSUE #37 

## 체크리스트

- [ ] 빌드 체크 하셨나요?
- [ ] PR의 내용을 짐작할 수 있는 적절한 제목을 썼나요?
- [ ] 작업 목적은 명확하게 의미 전달이 가능한가요?
- [ ] 작업 내용은 간결하게 끝나는 문장인가요?
- [ ] 첨부는 기능을 충분히 포함하고 있나요?
- [ ] 관련 이슈나 티켓, PR을 포함했나요?

2023-08-28 23:20 UTC, fepanbr reviewed
코멘트 확인부탁드립니다.

2023-08-28 23:20 UTC, fepanbr commented on prisma/schema.prisma
> +  birthDate DateTime @default(now()) @db.Date
birthDate의 기본값이 now가 괜찮을까요?

2023-08-28 23:20 UTC, fepanbr commented on src/app/registration/api/route.ts
> +  console.log('studentData? ::: ' + JSON.stringify(studentData));
콘솔제거 부탁드립니다.

2023-08-28 23:20 UTC, fepanbr commented on src/app/registration/api/route.ts
> +        agree: studentData.agree,
비구조화 할당으로 반복을 줄여보는 건 어떨까요?

2023-08-28 23:20 UTC, fepanbr commented on prisma/schema.prisma
> +  day Int[]
day도 enum으로 잡는건 어떤가요? 추후에 변경되지만 않으면 ENUM도 괜찮을 것 같습니다.

2023-08-29 09:17 UTC, fepanbr requested changes
agree 관련 내용 추가했습니다.

2023-08-29 09:17 UTC, fepanbr commented on prisma/schema.prisma
> +  agree Agree @default(NO)
해당 값은 Boolean으로 처리하는 건 어떨까요?

2023-08-29 14:46 UTC, GiSeok-Hong commented on src/app/registration/api/route.ts
> +  console.log('studentData? ::: ' + JSON.stringify(studentData));
작성된 콘솔 제거 하였습니다.

2023-08-29 15:46 UTC, GiSeok-Hong commented on prisma/schema.prisma
> +  agree Agree @default(NO)
해당 내용 반영했습니다!

2023-08-29 15:46 UTC, GiSeok-Hong commented on prisma/schema.prisma
> +  birthDate DateTime @default(now()) @db.Date
default 값은 제거 하겠습니다

2023-08-30 13:29 UTC, fepanbr approved these changes, later dismissed

2023-08-30 13:54 UTC, fepanbr approved these changes

2023-08-30 13:57 UTC, merged