Wonderart-CRM #50 학생 상세 페이지 구현
GiSeok-Hong/wonderart-crm pull request #55
Opened 2023-09-16 15:07 UTC by fepanbr

# Wonderart-CRM #50 학생 상세 페이지 구현

## 작업 목적
- 학생 상세 페이지를 구현합니다.

## 작업 내용
- 상세 페이지 validation
- PUT 메소드 구현
- api 경로 변경

## 해당 PR에서 테스트할 방법을 작성해 주세요
- [ ] 생년월일을 정확하게 입력하지 않으면 생년월일을 정확히 입력해주세요. alert이 뜬다.
- [ ] 입학날짜를 정확하게 입력하지 않으면 입학날짜를 정확히 입력해주세요. alert이 뜬다.
- [ ] 학생명을 정확하게 입력하지 않으면, 학생명을 정확히 입력해주세요. alert이 뜬다.
- [ ] 주소를 정확하게 입력하지 않으면, 주소를 정확히 입력해주세요. alert이 뜬다.
- [ ] 원더아트를 선택한 이유를 선택하지 않으면, 원더아트 스튜디오를 선택한 이유를 선택해주세요. alert이 뜬다.
- [ ] 학생 연락처를 정확하게 입력하지 않으면, 학생 연락처를 정확히 입력해주세요. alert이 뜬다.
- [ ] 보호자 연락처를 정확하게 입력하지 않으면, 보호자 연락처를 정확히 입력해주세요. alert이 뜬다.

## 첨부

## 관련된 이슈, 커밋, PR

- ISSUE #50

## 체크리스트

- [ ] 빌드 체크 하셨나요?
- [ ] PR의 내용을 짐작할 수 있는 적절한 제목을 썼나요?
- [ ] 작업 목적은 명확하게 의미 전달이 가능한가요?
- [ ] 작업 내용은 간결하게 끝나는 문장인가요?
- [ ] 첨부는 기능을 충분히 포함하고 있나요?
- [ ] 관련 이슈나 티켓, PR을 포함했나요?

2023-09-16 17:42 UTC, GiSeok-Hong requested changes
고생하셨습니다!

2023-09-16 17:42 UTC, GiSeok-Hong commented on src/app/api/student/[id]/route.ts
> +    return NextResponse.json({ message: '학생 정보 수정에 실패했습니다.' }, { status: 500 });
서버 에러메시지 형식을 통일하면 좋을 것 같은데 어떤 형식으로 통일할까요?

2023-09-16 17:42 UTC, GiSeok-Hong commented on src/consts/day-option.ts
> +  },
1. 수업 요일은 '월~금' 까지 입니다!
2. 일주일에 수업을 한 번만 듣는 학생도 있기에 '없음' 값도 필요하지 않을까요?
현재 학생 등록 페이지에서는 아래와 같이 되어 있습니다.
```
const DAY_OPTION = [
  {
    value: 0,
    name: '없음',
  },
  {
    value: 1,
    name: '월',
  },
  {
    value: 2,
    name: '화',
  },
  {
    value: 3,
    name: '수',
  },
  {
    value: 4,
    name: '목',
  },
  {
    value: 5,
    name: '금',
  },
];
```

2023-09-16 17:42 UTC, GiSeok-Hong commented on src/consts/time-option.ts
> +  {
현재 학생 등록 시 
```
value: 0,
name: '없음'
```
값도 있어서 해당 내용을 추가해야 할 것 같습니다.

2023-09-16 17:42 UTC, GiSeok-Hong commented on src/components/StudentDetailForm.tsx
> +                onChange: (e) => handleInputChange(e, 'entranceDate'),
input type을 date로 하여 입력 받는 형식은 별로 인가요?

2023-09-16 23:55 UTC, fepanbr commented on src/app/api/student/[id]/route.ts
> +    return NextResponse.json({ message: '학생 정보 수정에 실패했습니다.' }, { status: 500 });
길게 논의해봐야 할 것 같습니다! 같이 논의하면 좋을 것 같습니다.

2023-09-17 00:06 UTC, fepanbr commented on src/consts/day-option.ts
> +  },
1. 네 수정하겠습니다! 피드백 감사합니다.
2. 안그래도 이 부분을 논의해야할 부분이라고 생각했습니다. 현재 day를 배열로 받고 있는데, 배열에 값이 없다면, 수업이 없다고 생각하면 어떨까합니다. 그래서 UI 수정을 통해 처리하면 어떨까 합니다. 
예를 들면 시간, 날짜 입력 부분을 하나만 입력하도록 UI를 두고 수업 추가나 삭제 버튼을 통해 추가적인 날짜, 시간을 받던지 아니면 한번만 듣는 학생에 대한 처리를 할 수 있을 것 같습니다.

이 방식의 장점은 추후 저희가 사용하는 moment 라이브러리의 day값과 동일하게 매칭할 수 있어서 편리할 것 같습니다. 어떻게 생각하시나요?

2023-09-17 00:06 UTC, fepanbr commented on src/consts/time-option.ts
> +  {
위 커멘트에 대해 논의해보면 좋을 것 같습니다!

2023-09-17 00:08 UTC, fepanbr commented on src/components/StudentDetailForm.tsx
> +                onChange: (e) => handleInputChange(e, 'entranceDate'),
우선적으로 피그마 디자인 기준으로 작업하였습니다. 확인 못해서 죄송합니다.

제 개인적인 생각으론 input type date는 디자인 커스텀이 어렵고, UX적으로 입력방식이 어렵지 않나 생각이 듭니다. 
어떻게 생각하시나요?

2023-09-18 03:12 UTC, GiSeok-Hong commented on src/consts/day-option.ts
> +  },
좋은 생각입니다!
추가, 삭제 버튼 방식으로 처리하도록 하겠습니다.

2023-09-18 03:15 UTC, fepanbr commented on src/consts/day-option.ts
> +  },
네 수정해서 올리겠습니다!

2023-09-18 03:17 UTC, GiSeok-Hong commented on src/components/StudentDetailForm.tsx
> +                onChange: (e) => handleInputChange(e, 'entranceDate'),
말씀하신 대로 사용자가 직접 날짜를 입력하는 방식이 편한 것 같네요!

2023-09-18 03:50 UTC, GiSeok-Hong requested changes
추가 수정 요청합니다. 내용 확인해주세요.
감사합니다!

2023-09-18 03:50 UTC, GiSeok-Hong commented on src/components/StudentDetailForm.tsx
> +              {...register('name', { required: true })}
학생 이름 필드에 `maxLength=5` 가 누락되었습니다!

2023-09-18 03:50 UTC, GiSeok-Hong commented on src/components/StudentDetailForm.tsx
> +              {...register('guardianName')}
`maxLength=5` 누락되었습니다!

2023-09-18 03:50 UTC, GiSeok-Hong commented on src/components/StudentDetailForm.tsx
> +              {...register('address', { required: true })}
`maxLength=100` 누락되었습니다!

2023-09-18 03:50 UTC, GiSeok-Hong commented on src/components/StudentDetailForm.tsx
> +              {...register('school')}
`maxLength=20` 누락되었습니다!

2023-09-18 03:50 UTC, GiSeok-Hong commented on src/components/StudentDetailForm.tsx
> +            {...register('experience')}
`maxLength=100` 누락되었습니다!

2023-09-18 03:50 UTC, GiSeok-Hong commented on src/components/StudentDetailForm.tsx
> +            {...register('caution')}
`maxLength=200` 누락되었습니다!

2023-09-18 03:50 UTC, GiSeok-Hong commented on src/components/StudentDetailForm.tsx
> +            {...register('teacherMemo')}
`maxLength=200` 누락되었습니다!

2023-09-18 06:04 UTC, GiSeok-Hong approved these changes
수고하셨습니다!

2023-09-18 06:04 UTC, merged