Wonderart-CRM #64 선생님 등록 팝업 개발
GiSeok-Hong/wonderart-crm pull request #66
Opened 2023-09-26 10:18 UTC by fepanbr

# Wonderart-CRM #64 선생님 등록 팝업 개발

## 작업 목적
- 선생님 등록 팝업을 개발합니다.

## 작업 내용
- 선생님 등록 API 추가
- 선생님 등록 팝업 UI 개발
- 선생님 등록 팝업 기능 개발

## 해당 PR에서 테스트할 방법을 작성해 주세요

## 첨부
![선생님등록](https://github.com/GiSeok-Hong/wonderart-crm/assets/20733450/571e9226-cf3d-4fa2-9530-2cd037878d96)

## 관련된 이슈, 커밋, PR

- ISSUE #64
- 
## 체크리스트

- [ ] 빌드 체크 하셨나요?
- [ ] PR의 내용을 짐작할 수 있는 적절한 제목을 썼나요?
- [ ] 작업 목적은 명확하게 의미 전달이 가능한가요?
- [ ] 작업 내용은 간결하게 끝나는 문장인가요?
- [ ] 첨부는 기능을 충분히 포함하고 있나요?
- [ ] 관련 이슈나 티켓, PR을 포함했나요?

2023-09-27 11:05 UTC, GiSeok-Hong requested changes
고생 많으셨습니다!
코멘트 확인 부탁 드립니다.

2023-09-27 11:05 UTC, GiSeok-Hong commented on src/components/PlusButton.tsx
> +    <div className="fixed bottom-5 right-5">
right-10으로 줘서 통일감을 주면 좋을 것 같습니다!

2023-09-27 11:05 UTC, GiSeok-Hong commented on src/service/teacher.ts
> +        password: '1234',
비밀번호를 따로 입력 안 받는 이유가 있나요?

2023-09-27 14:00 UTC, fepanbr commented on src/service/teacher.ts
> +        password: '1234',
네 기획으로 정해진건 아니지만 생각해봤을 때 임의로 지정하는게 편할 것 같다는 생각이 들었습니다.
어떤 방식이 좋을까요?

2023-09-27 14:01 UTC, fepanbr commented on src/components/PlusButton.tsx
> +    <div className="fixed bottom-5 right-5">
네 수정하겠습니다

2023-09-28 06:04 UTC, GiSeok-Hong requested changes

2023-09-28 06:04 UTC, GiSeok-Hong commented on src/components/TeacherTable.tsx
> +              maxLength={50}
현재 email maxlength가 30이라 30으로 수정해주세요.

2023-09-28 06:04 UTC, GiSeok-Hong commented on src/service/teacher.ts
> +        password: '1234',
maxlength20으로 주고 이메일처럼 유저에게 입력 받으면 될 것 같습니다!

2023-09-30 04:06 UTC, fepanbr commented on src/service/teacher.ts
> +        password: '1234',
네 수정하겠습니다!

2023-09-30 04:12 UTC, fepanbr commented on src/service/teacher.ts
> +        password: '1234',
password는 특별히 권장하는 형식이 있을까요?

2023-09-30 05:37 UTC, GiSeok-Hong commented on src/service/teacher.ts
> +        password: '1234',
현재는 string으로 4글자 이상 20글자 이하로 받으면 될 것 같습니다!

2023-09-30 07:35 UTC, GiSeok-Hong approved these changes
고생 많으셨습니다!

2023-09-30 07:35 UTC, merged